version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/server"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/client"
    update_schedule: "weekly"

