# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, reopened, synchronize, edited, closed ]

jobs:
  server-build:

    runs-on: ubuntu-latest
    env:
      working-dir: ./server 

    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Server use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
      working-directory: ${{ env.working-dir }}
    - run: yarn build
      working-directory: ${{ env.working-dir }}
#    - run: npm test --if-present
#      working-directory: ${{ env.working-dir }}
      env:
        CI: true

  client-build:

    runs-on: ubuntu-latest
    env:
      working-dir: ./client

    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Client use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
      working-directory: ${{ env.working-dir }}
    - run: yarn build
      working-directory: ${{ env.working-dir }}
      env:
        CI: true
